server:
  port: 8080
  error.whitelabel.enabled: false

spring:
  main.banner-mode: 'off'
  mvc.throw-exception-if-no-handler-found: true
  resources.add-mappings: false

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/javasamplewebpaymentappdbdb
    username: postgres
    password: postgres

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
